import type { Metadata } from "next";
import { LegalH, LegalShell, LEGAL_CONTACT, LEGAL_SITE } from "@/components/marketing/LegalShell";

export const metadata: Metadata = {
  title: "Terms of Use — tidyAgent",
  description: "Terms of Use for the tidyAgent Wix app and hosted dashboard.",
};

export default function TermsPage() {
  return (
    <LegalShell eyebrow="Legal" title="Terms of Use">
      <p>
        These Terms of Use (“Terms”) govern access to and use of tidyAgent, including the Wix App Market listing,
        the hosted dashboard at {LEGAL_SITE}, the site chat widget, and related services (together, the “Service”).
        By installing the app, creating an account, or using the Service, you agree to these Terms.
      </p>

      <section className="space-y-3">
        <LegalH>1. Who we are</LegalH>
        <p>
          tidyAgent is an AI customer-service employee for Wix websites. It is provided as an externally hosted
          service. Wix is not the operator of tidyAgent and is not a party to these Terms, except that purchases
          made through the Wix App Market are also subject to Wix’s terms and billing rules.
        </p>
        <p>
          Questions:{" "}
          <a className="text-amber-300 hover:underline" href={`mailto:${LEGAL_CONTACT}`}>
            {LEGAL_CONTACT}
          </a>
          .
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>2. The Service</LegalH>
        <p>
          tidyAgent reads the connected Wix site (within the purchased plan’s scan scope), stores business knowledge,
          and uses that knowledge to reply to site visitors in a chat widget. Optional features, depending on plan,
          include specialist agents, automations, store catalog answers, and spoken replies.
        </p>
        <p>
          The Service is not a law firm, medical provider, or human employee. Answers are generated by software and
          may be incomplete or wrong. You remain responsible for your customer relationships, your website content,
          and any action you take based on the Service.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>3. Eligibility and accounts</LegalH>
        <p>
          You must have authority to install apps on the Wix site and to grant the permissions tidyAgent requests.
          You are responsible for account credentials, for people you invite, and for activity under your workspace.
        </p>
        <p>
          Opening tidyAgent from the Wix dashboard signs a session for that site instance. Each Wix site is a
          separate workspace. Do not share login details or attempt to access another site’s data.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>4. Plans, trials, and billing</LegalH>
        <p>
          Paid features require a Wix App Market plan (Starter, Business, or Pro). Wix processes payment. tidyAgent
          does not collect card details and does not bill through a separate checkout. A 7-day trial, if offered,
          is created and charged by Wix according to the listing you accept.
        </p>
        <p>
          What each plan can do (agent count, voice, automations, knowledge depth, and similar limits) is enforced
          by tidyAgent after Wix reports the purchase. Changing or cancelling a plan is done in Wix. Access continues
          until the current paid period ends when auto-renewal is turned off, unless Wix or these Terms say otherwise.
        </p>
        <p>
          Widget colors, greeting text, and similar basic setup are available on paid plans and are not sold as a
          separate checkout. Unpaid installs can open billing only until a plan is purchased.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>5. Your content and visitor conversations</LegalH>
        <p>
          You keep ownership of your site content, uploaded notes, agent names, photos, and similar materials you
          provide (“Your Content”). You grant tidyAgent a limited license to host, process, and display Your Content
          solely to provide the Service for your site.
        </p>
        <p>
          Site visitors’ messages are processed to generate replies, capture leads you enable, and show you
          conversation history. You must have a lawful basis to collect that information, including any notices and
          cookie/consent tools required on your Wix site.
        </p>
        <p>
          Do not use the Service to collect payment card numbers, government IDs, health data, or other sensitive
          categories unless you have a lawful basis and we have agreed in writing to support that use.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>6. AI output</LegalH>
        <p>
          tidyAgent is designed to answer from scanned site knowledge and the notes you add. It may still
          misread content, miss updates, or produce an unhelpful reply. You should review important answers,
          keep policies accurate on the live site, and use human handoff for complaints, refunds, and edge cases.
        </p>
        <p>
          Spoken replies use third-party text-to-speech providers. Voice quality and availability depend on those
          providers and on your plan.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>7. Acceptable use</LegalH>
        <p>You may not:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>probe, scrape, or overload the Service, or attempt to access another tenant’s data;</li>
          <li>use the widget to send spam, malware, or unlawful content;</li>
          <li>misrepresent the AI as a named human in a way that would deceive customers about who they are talking to;</li>
          <li>reverse engineer the Service except as allowed by law;</li>
          <li>use the Service in a way that would cause Wix or tidyAgent to break applicable law.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <LegalH>8. Third-party services</LegalH>
        <p>
          The Service relies on Wix APIs, AI model providers, optional image hosting, and optional speech providers.
          Their terms apply to their parts of the stack. An outage or change on Wix or a provider may affect tidyAgent.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>9. Intellectual property</LegalH>
        <p>
          tidyAgent, the dashboard, the widget code, and related trademarks remain ours or our licensors’. These
          Terms do not sell you the software. You may not copy the product, remove notices, or use our marks to
          imply we endorse your business.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>10. Privacy</LegalH>
        <p>
          How we collect and use personal data is described in the{" "}
          <a className="text-amber-300 hover:underline" href="/privacy">
            Privacy Policy
          </a>
          . If the two documents conflict on privacy topics, the Privacy Policy controls.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>11. Suspension and termination</LegalH>
        <p>
          You may stop using the Service and uninstall the app in Wix. We may suspend or close a workspace for
          unpaid access that is being abused, for security risk, or for a material breach of these Terms. After
          uninstall, we may delete or anonymize stored data after a reasonable retention period unless law requires
          longer storage.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>12. Disclaimers</LegalH>
        <p>
          THE SERVICE IS PROVIDED “AS IS.” TO THE FULLEST EXTENT ALLOWED BY LAW, WE DISCLAIM WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT UNINTERRUPTED
          OR ERROR-FREE OPERATION, OR THAT AI REPLIES WILL MATCH YOUR EXPECTATIONS.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>13. Limitation of liability</LegalH>
        <p>
          TO THE FULLEST EXTENT ALLOWED BY LAW, tidyAgent AND ITS OPERATORS ARE NOT LIABLE FOR INDIRECT, INCIDENTAL,
          SPECIAL, CONSEQUENTIAL, OR LOST-PROFIT DAMAGES, OR FOR LOST DATA. OUR TOTAL LIABILITY FOR CLAIMS ARISING
          OUT OF THE SERVICE IS LIMITED TO THE AMOUNTS PAID FOR tidyAgent THROUGH WIX FOR THE AFFECTED SITE IN THE
          THREE MONTHS BEFORE THE CLAIM.
        </p>
        <p>Some places do not allow these limits. In those places, liability is limited to the maximum the law allows.</p>
      </section>

      <section className="space-y-3">
        <LegalH>14. Changes</LegalH>
        <p>
          We may update these Terms. The “Last updated” date will change. Continued use after an update means you
          accept the new Terms. Material changes may also be noted in the dashboard or by email when we have an
          address.
        </p>
      </section>

      <section className="space-y-3">
        <LegalH>15. Contact</LegalH>
        <p>
          {LEGAL_CONTACT}
          <br />
          {LEGAL_SITE}
        </p>
      </section>
    </LegalShell>
  );
}
